# Generated by Django 4.2 on 2023-05-12 03:02

import Account.models
import ckeditor.fields
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "firstname",
                    models.CharField(max_length=50, verbose_name="Firstname"),
                ),
                ("lastname", models.CharField(max_length=50, verbose_name="Lastname")),
                (
                    "user_type",
                    models.CharField(
                        choices=[("Individual", "Agency"), ("Agency", "Agency")],
                        max_length=50,
                        verbose_name="User Type",
                    ),
                ),
                (
                    "id_passport",
                    models.CharField(max_length=50, verbose_name="ID/Passport"),
                ),
                ("slug", models.UUIDField(default=uuid.uuid4, editable=False)),
                (
                    "tell",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Phone Number",
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("Male", "Male"),
                            ("Female", "Female"),
                            ("Prefer not to say", "Prefer not to say"),
                        ],
                        max_length=50,
                        verbose_name="Gender",
                    ),
                ),
                (
                    "dob",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date Of Birth"
                    ),
                ),
                (
                    "county",
                    models.CharField(
                        choices=[
                            ("Mombasa", "Mombasa"),
                            ("Kwale", "Kwale"),
                            ("Kilifi", "Kilifi"),
                            ("TanaRiver", "Tana River"),
                            ("Lamu", "Lamu"),
                            ("Taita-Taveta", "Taita-Taveta"),
                            ("Garissa", "Garissa"),
                            ("Wajir", "Wajir"),
                            ("Mandera", "Mandera"),
                            ("Marsabit", "Marsabit"),
                            ("Isiolo", "Isiolo"),
                            ("Meru", "Meru"),
                            ("Tharaka Nithi", "Tharaka-Nithi"),
                            ("Embu", "Embu"),
                            ("Kitui", "Kitui"),
                            ("Machakos", "Machakos"),
                            ("Makueni", "Makueni"),
                            ("Nyandarua", "Nyandarua"),
                            ("Nyeri", "Nyeri"),
                            ("Kirinyaga", "Kirinyaga"),
                            ("Muranga", "Murang'a"),
                            ("Kiambu", "Kiambu"),
                            ("Turkana", "Turkana"),
                            ("WestPokot", " West Pokot"),
                            ("Samburu", "Samburu"),
                            ("TransNzoia", "Trans Nzoia"),
                            ("Uasin Gishu", "Uasin Gishu"),
                            ("Elgeyo-Marakwet", "Elgeyo-Marakwet"),
                            ("Nandi ", "Nandi"),
                            ("Baringo", "Baringo"),
                            ("Laikipia", "Laikipia"),
                            ("Nakuru", "Nakuru"),
                            ("Narok", "Narok"),
                            ("Kajiado", "Kajiado"),
                            ("Kericho", "Kericho"),
                            ("Bomet", "Bomet"),
                            ("Kakamega", "Kakamega"),
                            ("Vihiga", "Vihiga"),
                            ("Bungoma", "Bungoma"),
                            ("Busia", "Busia"),
                            ("Siaya", "Siaya"),
                            ("Kisumu ", "Kisumu"),
                            ("HomaBay", "Homa Bay"),
                            ("Migori", "Migori"),
                            ("Kisii", "Kisii"),
                            ("Nyamira", "Nyamira"),
                            ("Nairobi", "Nairobi"),
                        ],
                        max_length=50,
                        verbose_name="County",
                    ),
                ),
                ("location", models.CharField(max_length=50, verbose_name="Location")),
                ("address", models.CharField(max_length=50, verbose_name="Address")),
                ("skills", models.CharField(max_length=50, verbose_name="Skills")),
                ("bio", ckeditor.fields.RichTextField()),
                (
                    "profile",
                    models.ImageField(
                        blank=True,
                        default="default_profile.png",
                        null=True,
                        upload_to=Account.models.user_profile_path,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["jpg", "png", "jpeg"]
                            )
                        ],
                        verbose_name="Profile Picture",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        default="Active", max_length=50, verbose_name="Status"
                    ),
                ),
                (
                    "is_suspended",
                    models.BooleanField(default=False, verbose_name="Suspended"),
                ),
                (
                    "twitter",
                    models.URLField(blank=True, null=True, verbose_name="Twitter"),
                ),
                (
                    "facebook",
                    models.URLField(blank=True, null=True, verbose_name="Facebook"),
                ),
                (
                    "instagram",
                    models.URLField(blank=True, null=True, verbose_name="Instagram"),
                ),
                (
                    "website",
                    models.URLField(blank=True, null=True, verbose_name="Website"),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Profile",
                "verbose_name_plural": "Profiles",
            },
        ),
        migrations.CreateModel(
            name="ProfileCV",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cv",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=Account.models.user_documents_path,
                        validators=[
                            django.core.validators.FileExtensionValidator(["pdf"])
                        ],
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile_cv",
                        to="Account.profile",
                        verbose_name="",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="",
                    ),
                ),
            ],
            options={
                "verbose_name": "ProfileCV",
                "verbose_name_plural": "ProfileCVs",
            },
        ),
    ]
