# Generated by Django 4.2 on 2023-05-12 04:06

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Account", "0002_alter_profile_profile_alter_profile_user_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="dob",
            field=models.DateField(
                default=datetime.datetime(
                    2023, 5, 12, 4, 5, 54, 642744, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Date Of Birth",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="profile",
            name="profile",
            field=models.ImageField(
                default="default_profile.png",
                upload_to="profiles",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["jpg", "png", "jpeg"]
                    )
                ],
                verbose_name="Profile Picture",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="tell",
            field=phonenumber_field.modelfields.PhoneNumberField(
                default="+254712456789", max_length=128, region=None
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="profilecv",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile_cv",
                to="Account.profile",
            ),
        ),
        migrations.AlterField(
            model_name="profilecv",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
