# Generated by Django 4.2 on 2023-05-12 07:11

import Account.models
import datetime
import django.core.validators
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):
    dependencies = [
        ("Account", "0003_alter_profile_dob_alter_profile_profile_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profilecv",
            name="user",
        ),
        migrations.AddField(
            model_name="profilecv",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2023, 5, 12, 7, 11, 27, 908486, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="profile",
            name="dob",
            field=models.DateField(
                validators=[Account.models.validate_age], verbose_name="Date Of Birth"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="id_passport",
            field=models.CharField(
                max_length=10,
                unique=True,
                validators=[django.core.validators.MinLengthValidator(6)],
                verbose_name="ID/Passport",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="tell",
            field=phonenumber_field.modelfields.PhoneNumberField(
                max_length=128, region=None, unique=True
            ),
        ),
    ]
