# Generated by Django 4.2 on 2023-05-12 07:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Account", "0005_profilecv_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profilecv",
            name="cv",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="documents",
                validators=[django.core.validators.FileExtensionValidator(["pdf"])],
            ),
        ),
    ]
