# Generated by Django 4.2 on 2023-05-12 07:35

import Account.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Account", "0006_alter_profilecv_cv"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profilecv",
            name="cv",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=Account.models.user_documents_path,
                validators=[django.core.validators.FileExtensionValidator(["pdf"])],
            ),
        ),
    ]
