# Generated by Django 4.2 on 2023-05-12 07:39

import Account.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Account", "0007_alter_profilecv_cv"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="dob",
            field=models.DateField(
                blank=True,
                null=True,
                validators=[Account.models.validate_age],
                verbose_name="Date Of Birth",
            ),
        ),
    ]
