# Generated by Django 4.2 on 2023-05-12 07:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Account", "0008_alter_profile_dob"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile",
            field=models.ImageField(
                default="profiles/default_profile.png",
                upload_to="profiles",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["jpg", "png", "jpeg"]
                    )
                ],
                verbose_name="Profile Picture",
            ),
        ),
    ]
