# Generated by Django 4.2 on 2023-05-12 07:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Account", "0009_alter_profile_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="id_passport",
            field=models.CharField(
                blank=True,
                max_length=10,
                null=True,
                unique=True,
                validators=[django.core.validators.MinLengthValidator(6)],
                verbose_name="ID/Passport",
            ),
        ),
    ]
