# Generated by Django 4.2 on 2023-05-30 02:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Account", "0011_alter_profile_tell"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="experience",
            field=models.IntegerField(
                blank=True, max_length=50, null=True, verbose_name="Years of Experience"
            ),
        ),
    ]
