# Generated by Django 4.2 on 2023-06-01 02:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Account", "0013_alter_profile_experience"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="title",
            field=models.CharField(
                default="PLumber", max_length=50, verbose_name="Job Title"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="profile",
            name="experience",
            field=models.IntegerField(default=0, verbose_name="Years of Experience"),
        ),
    ]
