# Generated by Django 4.2 on 2023-06-28 06:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Account", "0017_education_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="education",
            name="institution",
            field=models.TextField(default="Cabel", verbose_name="Institution"),
            preserve_default=False,
        ),
    ]
