# Generated by Django 4.2 on 2023-06-28 17:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Account", "0018_education_institution"),
    ]

    operations = [
        migrations.AlterField(
            model_name="education",
            name="course",
            field=models.CharField(verbose_name="Course"),
        ),
        migrations.AlterField(
            model_name="education",
            name="description",
            field=models.TextField(
                blank=True, max_length=250, null=True, verbose_name="Description"
            ),
        ),
        migrations.AlterField(
            model_name="education",
            name="institution",
            field=models.CharField(verbose_name="Institution"),
        ),
    ]
