# Generated by Django 4.2 on 2023-06-29 04:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Account", "0019_alter_education_course_alter_education_description_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Experience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150, verbose_name="Title")),
                ("employer", models.CharField(max_length=50, verbose_name="Employer")),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Explain Your Role"
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Start Date")),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="End Date"),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Experience",
                "verbose_name_plural": "Experiences",
            },
        ),
    ]
