# Generated by Django 4.2 on 2023-07-06 14:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Account", "0021_experience_slug_experience_user_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="education",
            name="course",
            field=models.CharField(max_length=256, verbose_name="Course"),
        ),
        migrations.AlterField(
            model_name="education",
            name="institution",
            field=models.CharField(max_length=256, verbose_name="Institution"),
        ),
    ]
