# Generated by Django 4.2 on 2023-07-26 03:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Account", "0022_alter_education_course_alter_education_institution"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rating",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_ratee",
                to="Account.profile",
            ),
        ),
        migrations.AlterField(
            model_name="rating",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rater",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
