# Generated by Django 4.2 on 2023-10-04 04:39

import Account.models
import Account.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Account", "0023_alter_rating_profile_alter_rating_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="education",
            name="end_date",
            field=models.DateField(blank=True, null=True, verbose_name="End Date"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="profile",
            field=models.ImageField(
                default="profiles/default_profile.png",
                upload_to="profiles",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["jpg", "png", "jpeg"]
                    ),
                    Account.validators.validate_file_size,
                ],
                verbose_name="Profile Picture",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="title",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Job Title"
            ),
        ),
        migrations.AlterField(
            model_name="profilecv",
            name="cv",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=Account.models.user_documents_path,
                validators=[
                    django.core.validators.FileExtensionValidator(["pdf"]),
                    Account.validators.validate_file_size,
                ],
            ),
        ),
    ]
