# Generated by Django 4.2 on 2023-06-07 02:33

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Page", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Faq",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50, verbose_name="Title")),
                (
                    "slug",
                    django_extensions.db.fields.AutoSlugField(
                        blank=True, editable=False, populate_from="title"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Genera", "General"),
                            ("Payments", "Payments"),
                            ("Job Application", "Job Application"),
                            ("Support", "Support"),
                        ],
                        max_length=50,
                        verbose_name="Category",
                    ),
                ),
                ("content", ckeditor.fields.RichTextField(verbose_name="Content")),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="faq_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Faq",
                "verbose_name_plural": "Faqs",
            },
        ),
    ]
