# Generated by Django 4.2 on 2023-05-16 09:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Application", "0003_alter_application_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="status",
            field=models.CharField(db_index=True, default="Pending", max_length=50),
        ),
    ]
