# Generated by Django 4.2 on 2023-05-31 06:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Application", "0004_alter_application_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="approved_canceled_time",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Approved / Rejected time"
            ),
        ),
    ]
