# Generated by Django 4.2 on 2023-06-01 02:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Application", "0005_application_approved_canceled_time"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="application",
            options={
                "ordering": ["-approved_canceled_time"],
                "verbose_name": "Application",
                "verbose_name_plural": "Applications",
            },
        ),
    ]
