# Generated by Django 4.2 on 2023-06-24 10:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Application", "0008_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rating",
            name="ratings",
            field=models.TextField(
                choices=[("1", "1"), ("2", "2"), ("3", "3"), ("4", "4"), ("5", "5")],
                verbose_name="Ratings",
            ),
        ),
    ]
