# Generated by Django 4.2 on 2023-06-24 10:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Application", "0009_alter_rating_ratings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rating",
            name="ratings",
            field=models.IntegerField(
                choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name="Ratings"
            ),
        ),
    ]
