# Generated by Django 4.2 on 2023-09-23 05:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Job", "0024_alter_job_reference_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Application", "0012_alter_application_charge_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="application",
            unique_together={("user", "job")},
        ),
    ]
