# Generated by Django 4.2 on 2023-07-27 19:03

import Blog.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="photo",
            field=models.ImageField(
                upload_to="blogs",
                validators=[
                    Blog.validators.validate_file_size,
                    django.core.validators.FileExtensionValidator(
                        ["jpg", "png", "jpeg", "gif"]
                    ),
                ],
                verbose_name="Photo",
            ),
        ),
    ]
