# Generated by Django 4.2 on 2023-07-28 03:07

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):
    dependencies = [
        ("taggit", "0005_auto_20220424_2025"),
        ("Blog", "0003_taggedblog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="tags",
            field=taggit.managers.TaggableManager(
                help_text="A comma-separated list of tags.",
                through="Blog.TaggedBlog",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
    ]
