# Generated by Django 4.2 on 2023-07-28 03:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Blog", "0004_alter_blog_tags"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blog",
            name="tags",
        ),
        migrations.DeleteModel(
            name="TaggedBlog",
        ),
    ]
