# Generated by Django 4.2 on 2023-07-28 07:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Blog", "0005_remove_blog_tags_delete_taggedblog"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blog",
            name="bookmarks",
        ),
        migrations.RemoveField(
            model_name="blog",
            name="likes",
        ),
    ]
