# Generated by Django 4.2 on 2023-08-02 04:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Blog", "0007_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="created",
            field=models.DateField(auto_now_add=True, verbose_name="Created"),
        ),
        migrations.AlterField(
            model_name="blog",
            name="updated",
            field=models.DateField(auto_now=True, verbose_name="Updated"),
        ),
        migrations.AlterField(
            model_name="comment",
            name="created",
            field=models.DateField(auto_now_add=True),
        ),
    ]
