COUNTY= [
        ('Mombasa', 'Mombasa'),
        ('Kwale', 'Kwale'),
        ('Kilifi', 'Kilifi'),
        ('TanaRiver', 'Tana River'),
        ('Lamu', 'Lamu'),
        ('Taita-Taveta', 'Taita-Taveta'),
        ('Garissa' ,'Garissa'),
        ('Wajir', 'Wajir'),
        ('Mandera', 'Mandera'),
        ('Marsabit', 'Marsabit'),
        ('Isiolo', 'Isiolo'),
        ('Meru', 'Meru'),
        ('Tharaka Nithi', 'Tharaka-Nithi'),
        ('Embu', 'Embu'),
        ('Kitui' ,'Kitui'),
        ('Machakos', 'Machakos'),
        ('Makueni', 'Makueni'),
        ('Nyandarua', 'Nyandarua'),
        ('Nyeri', 'Nyeri'),
        ('Kirinyaga','Kirinyaga'),
        ('Muranga',"Murang'a"),
        ('Kiambu', 'Kiambu'),
        ('Turkana' ,'Turkana'),
        ('WestPokot',' West Pokot'),
        ('Samburu', 'Samburu'),
        ('TransNzoia' ,'Trans Nzoia'),
        ('Uasin Gishu', 'Uasin Gishu'),
        ('Elgeyo-Marakwet', 'Elgeyo-Marakwet'),
        ('Nandi ','Nandi'),
        ('Baringo', 'Baringo'),
        ('Laikipia' ,'Laikipia'),
        ('Nakuru', 'Nakuru'),
        ('Narok', 'Narok'),
        ('Kajiado', 'Kajiado'),
        ('Kericho', 'Kericho'),
        ('Bomet', 'Bomet'),
        ('Kakamega' ,'Kakamega'),
        ('Vihiga', 'Vihiga'),
        ('Bungoma', 'Bungoma'),
        ('Busia', 'Busia'),
        ('Siaya', 'Siaya'),
        ('Kisumu ','Kisumu'),
        ('HomaBay', 'Homa Bay'),
        ('Migori', 'Migori'),
        ('Kisii', 'Kisii'),
        ('Nyamira', 'Nyamira'),
        ('Nairobi', 'Nairobi'),
    ]
MY_GENDER = [
    ("Male", "Male"),
    ("Female", "Female"),
    ("Prefer not to say", "Prefer not to say"),
]
USER_TYPE = [
    ('Individual', 'Individual'),
    ('Agency', 'Agency'),
]
RATINGS = [
    (1, 1),
    (2, 2),
    (3, 3),
    (4, 4), 
    (5, 5)
    ]

