# Generated by Django 4.2 on 2023-05-03 18:24

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import taggit.managers


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("taggit", "0005_auto_20220424_2025"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                (
                    "slug",
                    django_extensions.db.fields.AutoSlugField(
                        blank=True, editable=False, populate_from="name"
                    ),
                ),
                ("description", models.TextField(max_length=250)),
                ("is_published", models.BooleanField(default=True)),
                ("is_featured", models.BooleanField(default=False)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events_category",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categorys",
            },
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reference_id", models.IntegerField(verbose_name="reference_id")),
                ("title", models.CharField(max_length=50, verbose_name="Title")),
                (
                    "slug",
                    django_extensions.db.fields.AutoSlugField(
                        blank=True, editable=False, populate_from="title"
                    ),
                ),
                ("content", ckeditor.fields.RichTextField(verbose_name="Description")),
                ("deadline", models.DateTimeField(verbose_name="Application Deadline")),
                ("job_end_time", models.DateTimeField(verbose_name="To be done time")),
                ("skills", ckeditor.fields.RichTextField(verbose_name="Skills")),
                (
                    "job_type",
                    models.CharField(
                        choices=[("Contract", "Contract"), ("Fulltime", "Fulltime")],
                        max_length=50,
                        verbose_name="Job type",
                    ),
                ),
                (
                    "seeker_type",
                    models.CharField(
                        choices=[
                            ("Individual", "Individual"),
                            ("Company", "Company"),
                            ("Open", "Open"),
                        ],
                        max_length=50,
                        verbose_name="Seeker Type",
                    ),
                ),
                ("positions", models.IntegerField(verbose_name="Available position")),
                (
                    "county",
                    models.CharField(
                        choices=[
                            ("Mombasa", "Mombasa"),
                            ("Kwale", "Kwale"),
                            ("Kilifi", "Kilifi"),
                            ("TanaRiver", "Tana River"),
                            ("Lamu", "Lamu"),
                            ("Taita-Taveta", "Taita-Taveta"),
                            ("Garissa", "Garissa"),
                            ("Wajir", "Wajir"),
                            ("Mandera", "Mandera"),
                            ("Marsabit", "Marsabit"),
                            ("Isiolo", "Isiolo"),
                            ("Meru", "Meru"),
                            ("Tharaka Nithi", "Tharaka-Nithi"),
                            ("Embu", "Embu"),
                            ("Kitui", "Kitui"),
                            ("Machakos", "Machakos"),
                            ("Makueni", "Makueni"),
                            ("Nyandarua", "Nyandarua"),
                            ("Nyeri", "Nyeri"),
                            ("Kirinyaga", "Kirinyaga"),
                            ("Muranga", "Murang'a"),
                            ("Kiambu", "Kiambu"),
                            ("Turkana", "Turkana"),
                            ("WestPokot", " West Pokot"),
                            ("Samburu", "Samburu"),
                            ("TransNzoia", "Trans Nzoia"),
                            ("Uasin Gishu", "Uasin Gishu"),
                            ("Elgeyo-Marakwet", "Elgeyo-Marakwet"),
                            ("Nandi ", "Nandi"),
                            ("Baringo", "Baringo"),
                            ("Laikipia", "Laikipia"),
                            ("Nakuru", "Nakuru"),
                            ("Narok", "Narok"),
                            ("Kajiado", "Kajiado"),
                            ("Kericho", "Kericho"),
                            ("Bomet", "Bomet"),
                            ("Kakamega", "Kakamega"),
                            ("Vihiga", "Vihiga"),
                            ("Bungoma", "Bungoma"),
                            ("Busia", "Busia"),
                            ("Siaya", "Siaya"),
                            ("Kisumu ", "Kisumu"),
                            ("HomaBay", "Homa Bay"),
                            ("Migori", "Migori"),
                            ("Kisii", "Kisii"),
                            ("Nyamira", "Nyamira"),
                            ("Nairobi", "Nairobi"),
                        ],
                        max_length=50,
                        verbose_name="County",
                    ),
                ),
                (
                    "location",
                    models.CharField(max_length=50, verbose_name="Location/Town/City"),
                ),
                ("address", models.CharField(max_length=50, verbose_name="Address")),
                ("status", models.BooleanField(default="Open")),
                ("is_featured", models.BooleanField(default=True)),
                ("is_published", models.BooleanField(default=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Job.category",
                        verbose_name="",
                    ),
                ),
                (
                    "tags",
                    taggit.managers.TaggableManager(
                        help_text="A comma-separated list of tags.",
                        through="taggit.TaggedItem",
                        to="taggit.Tag",
                        verbose_name="Tags",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="",
                    ),
                ),
            ],
            options={
                "verbose_name": "Job",
                "verbose_name_plural": "Jobs",
            },
        ),
    ]
