# Generated by Django 4.2 on 2023-05-04 03:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Job", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="reference_id",
            field=models.IntegerField(
                blank=True, unique=True, verbose_name="reference_id"
            ),
        ),
    ]
