# Generated by Django 4.2 on 2023-05-04 06:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Job", "0004_alter_job_reference_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="job_category",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="seeker_type",
            field=models.CharField(
                choices=[("Individual", "Individual"), ("Company", "Company")],
                max_length=50,
                verbose_name="Seeker Type",
            ),
        ),
    ]
