# Generated by Django 4.2 on 2023-05-04 06:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Job", "0005_alter_category_user_alter_job_seeker_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="status",
            field=models.CharField(default="Open"),
        ),
    ]
