# Generated by Django 4.2 on 2023-05-16 09:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Job", "0008_alter_job_options_alter_job_category_savedjob"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="county",
            field=models.CharField(
                choices=[
                    ("Mombasa", "Mombasa"),
                    ("Kwale", "Kwale"),
                    ("Kilifi", "Kilifi"),
                    ("TanaRiver", "Tana River"),
                    ("Lamu", "Lamu"),
                    ("Taita-Taveta", "Taita-Taveta"),
                    ("Garissa", "Garissa"),
                    ("Wajir", "Wajir"),
                    ("Mandera", "Mandera"),
                    ("Marsabit", "Marsabit"),
                    ("Isiolo", "Isiolo"),
                    ("Meru", "Meru"),
                    ("Tharaka Nithi", "Tharaka-Nithi"),
                    ("Embu", "Embu"),
                    ("Kitui", "Kitui"),
                    ("Machakos", "Machakos"),
                    ("Makueni", "Makueni"),
                    ("Nyandarua", "Nyandarua"),
                    ("Nyeri", "Nyeri"),
                    ("Kirinyaga", "Kirinyaga"),
                    ("Muranga", "Murang'a"),
                    ("Kiambu", "Kiambu"),
                    ("Turkana", "Turkana"),
                    ("WestPokot", " West Pokot"),
                    ("Samburu", "Samburu"),
                    ("TransNzoia", "Trans Nzoia"),
                    ("Uasin Gishu", "Uasin Gishu"),
                    ("Elgeyo-Marakwet", "Elgeyo-Marakwet"),
                    ("Nandi ", "Nandi"),
                    ("Baringo", "Baringo"),
                    ("Laikipia", "Laikipia"),
                    ("Nakuru", "Nakuru"),
                    ("Narok", "Narok"),
                    ("Kajiado", "Kajiado"),
                    ("Kericho", "Kericho"),
                    ("Bomet", "Bomet"),
                    ("Kakamega", "Kakamega"),
                    ("Vihiga", "Vihiga"),
                    ("Bungoma", "Bungoma"),
                    ("Busia", "Busia"),
                    ("Siaya", "Siaya"),
                    ("Kisumu ", "Kisumu"),
                    ("HomaBay", "Homa Bay"),
                    ("Migori", "Migori"),
                    ("Kisii", "Kisii"),
                    ("Nyamira", "Nyamira"),
                    ("Nairobi", "Nairobi"),
                ],
                db_index=True,
                max_length=50,
                verbose_name="County",
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="created",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="job",
            name="deadline",
            field=models.DateTimeField(
                db_index=True, verbose_name="Application Deadline"
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="is_featured",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name="job",
            name="is_published",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name="job",
            name="job_end_time",
            field=models.DateTimeField(db_index=True, verbose_name="To be done time"),
        ),
        migrations.AlterField(
            model_name="job",
            name="location",
            field=models.CharField(
                db_index=True, max_length=50, verbose_name="Location/Town/City"
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="status",
            field=models.CharField(db_index=True, default="Open", max_length=50),
        ),
    ]
