# Generated by Django 4.2 on 2023-05-16 11:20

import django.contrib.postgres.indexes
from django.db import migrations
from django.contrib.postgres.operations import BtreeGinExtension

class Migration(migrations.Migration):
    dependencies = [
        ("Job", "0009_alter_job_county_alter_job_created_and_more"),
    ]

    operations = [
        BtreeGinExtension(),
        migrations.AddIndex(
            model_name="job",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["title"], name="NewGinIndex"
            ),
        ),
    ]
