# Generated by Django 4.2 on 2023-05-16 11:27

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Job", "0010_job_newginindex"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="job",
            name="NewGinIndex",
        ),
        migrations.AddIndex(
            model_name="job",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["title"], name="NewGinIndex", opclasses=["gin_trgm_ops"]
            ),
        ),
    ]
