# Generated by Django 4.2 on 2023-05-18 06:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Job", "0011_remove_job_newginindex_job_newginindex"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="industry",
            field=models.CharField(
                choices=[("Contract", "Contract"), ("Fulltime", "Fulltime")],
                default="Hotel",
                max_length=50,
                verbose_name="Industry",
            ),
            preserve_default=False,
        ),
    ]
