# Generated by Django 4.2 on 2023-05-23 06:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Job", "0013_alter_job_industry"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="title",
            field=models.CharField(max_length=150, verbose_name="Title"),
        ),
    ]
