# Generated by Django 4.2 on 2023-05-28 10:17

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Job", "0014_alter_job_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="qualification",
            field=ckeditor.fields.RichTextField(
                blank=True, null=True, verbose_name="Qualification"
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="responsibility",
            field=ckeditor.fields.RichTextField(
                default="ff", verbose_name="Responsibility"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="job",
            name="seeker_type",
            field=models.CharField(
                choices=[
                    ("Individuals", "Individuals"),
                    ("Agencies", "Agencies"),
                    ("Any", "Any"),
                ],
                max_length=50,
                verbose_name="Seeker Type",
            ),
        ),
    ]
