# Generated by Django 4.2 on 2023-05-28 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("Job", "0015_job_qualification_job_responsibility_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobimage",
            name="job",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="job_images",
                to="Job.job",
                verbose_name="",
            ),
        ),
    ]
