# Generated by Django 4.2 on 2023-06-23 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("Job", "0018_alter_savedjob_job"),
    ]

    operations = [
        migrations.AlterField(
            model_name="savedjob",
            name="job",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="savedJobs",
                to="Job.job",
            ),
        ),
    ]
