# Generated by Django 4.2 on 2023-06-25 08:21

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Job", "0019_alter_savedjob_job"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="jobimage",
            name="image",
        ),
        migrations.AddField(
            model_name="jobimage",
            name="Job Images",
            field=cloudinary.models.CloudinaryField(
                default="bucegi-mountains-1641852_4oLrGHT.jpg",
                max_length=255,
                verbose_name="image",
            ),
            preserve_default=False,
        ),
    ]
