# Generated by Django 4.2 on 2023-06-25 08:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Job", "0020_remove_jobimage_image_jobimage_job_images"),
    ]

    operations = [
        migrations.RenameField(
            model_name="jobimage",
            old_name="Job Images",
            new_name="image",
        ),
    ]
