# Generated by Django 4.2 on 2023-07-17 06:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Job", "0022_alter_job_content_alter_job_positions"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="job",
            name="positions",
        ),
    ]
