# Generated by Django 4.2 on 2023-09-26 06:34

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("Job", "0024_alter_job_reference_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Complaints",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50, verbose_name="Title")),
                (
                    "subject",
                    models.CharField(
                        choices=[
                            ("Suggestion", "Suggestion"),
                            ("Complaints", "Complaints"),
                        ],
                        max_length=50,
                        verbose_name="Subject",
                    ),
                ),
                (
                    "description",
                    ckeditor.fields.RichTextField(verbose_name="Description"),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_complaints",
                        to="Job.job",
                        verbose_name="",
                    ),
                ),
            ],
            options={
                "verbose_name": "Complaints",
                "verbose_name_plural": "Complaints",
            },
        ),
    ]
