# Generated by Django 4.2 on 2023-09-26 06:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Job", "0025_complaints"),
    ]

    operations = [
        migrations.AddField(
            model_name="complaints",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="",
            ),
            preserve_default=False,
        ),
    ]
